#!/usr/bin/bash

docker_deb="https://desktop.docker.com/linux/main/amd64/145265/docker-desktop-4.29.0-amd64.deb?utm_source=docker&utm_medium=webreferral&utm_campaign=docs-driven-download-linux-amd64&_gl=1*fzmtvt*_ga*NTI2Nzk0NDg5LjE3MDk3Mjc4MTQ.*_ga_XJWPQMJYHQ*MTcxMjk5NzQ3MC40NC4xLjE3MTMwMDE1NDAuNDcuMC4w"
rm_auto_aim_repository="https://github.com/yxSakana/rm_auto_aim.git"
repository_docker_path="src/auto_aim"

# Install Docker
# Add Docker's official GPG key:
sudo apt-get update
sudo apt-get install ca-certificates curl -y
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc
# Add the repository to Apt sources:
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update
# Docker Engine
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y

# Build image by Dockerfile
git clone "https://github.com/yxSakana/"${rm_auto_aim_repository}".git" --depth=1
cd ${rm_auto_aim_repository}/${repository_docker_path}
docker build .

# Configure program to run at system startup
cp $0/rm_auto_aim.serivice /etc/systemd/system
sudo systemctl daemon-reload
sudo systemctl enable rm_auto_aim
