#!/bin/bash

docker run \
    --privileged \
    --device=/dev/dri \
    --device=/dev/ttyACM0 \
    --volume=/dev/bus/usb \
    --volume=/dev/ttyACM0 \
    --volume=/tmp/.X11-unix \
    --name rm_auto_aim \
    rm_auto_aim
